---
name: ansible-lint-next
description: Run Ansible Lint (next)
author: Ansible by Red Hat <info@ansible.com>
branding:
  icon: shield
  color: red
inputs:
  path:
    description: >
      Specific path to lint instead of the default `.`. Multiple arguments are
      not supported and you will need to alter linter configuration to
      accommodate other use cases.
    required: false
    # That default is just a placeholder workaround for no arguments use-case
    # Feeding "." or empty string to ansible-lint makes it believe it is a role
    default: --show-relpath
  args:
    description: deprecated
    deprecationMessage: >
      Arbitrary args are no longer accepted, please use path instead and
      linter own configuration file to change its behavior.
    required: false
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # needed by setuptools-scm
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        cache: pip
        python-version: "3.11"

    - name: Install ansible-lint
      shell: bash
      run: |
        echo "repo: ${{ github.action_repository }}"
        echo "action_ref: ${{ github.action_repository }}"

        cd ${{ github.action_path }}
        # git fetch --prune --unshallow --no-tags || true
        # pipx install -e ".[lock]" | tee -a $GITHUB_STEP_SUMMARY
        pip install git+https://github.com/ansible/ansible-lint@${{ github.action_ref || 'main' }}
        ansible-lint --version

    - name: Run ansible-lint
      shell: bash
      run: ansible-lint ${{ inputs.path }}
